language: cpp

compiler:
  - clang
  - gcc

sudo: required

services:
  - docker

env:
  global:
    # DEPLOY_HOST
    - secure: "niONbfXjsOy5Gyom7Xogh0NZpj25ajVF4+0uIuOgahqWY9SZ8UEC+QqMyFTt5T9VB07HCltozIP1+A5fioqjQqXr97txfPTAmuowqOJ1CR8jLZGe7DwBgLo46DuGT5dyj4mqRYMgharZexmJd+LTm2GHwG8IgvVZleUMiWjtzn8lT1R7qaBoDH5YGsBvTqlTa87nGIV8DGj+cK509jsdUI5qG8LBOkCqbh9kYcFVY+a4M99UXHZS2KMgdCPwFUCZzxWnixLXHSdif4GG2Geu/1TH8W7EVqsc3qwQNyTf3lEgrDT9ahath6dCVCTH6KNCgNDBBeFkwxcAcxP182sBMijGmVZc5IrSFkhJhJ69v9UDViX2tqtb4nKuAtyOx2fNJdByiDWvTAbnm/rKUUwIxeanyjCIBaiIVNOqbFTbKk4GmMu+Gz5tIEPHNXelgZhOA04v+ynWDAdYz/pesbUGnB2HOuWIZkm/Bc6pO5chogLlWB/3Vr4LzdA5Qd49MmuSzx1XpnY0StXuoUkULRUaKFykn4h3CaeppANjnCJDJ+EhuJKN5PFfU+BuPh2w2fX6mN5aDb0xdszqVmUDRfccQc2hZECU1xopl/m/bm5/I0Z2Z5xz30r8ypHCCD/h9C9GaWZnoWoGJgZWqFwPL43mVWq9Tv8QhNM5W1rEcPnd3U4="

branches:
  except:
    - /^(?i:continuous)$/

script:
  - wget -c https://raw.githubusercontent.com/lirios/infra-travis/master/run
  - bash run ./.travis/build.sh

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
